// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcPlayers.Data;

#nullable disable

namespace MvcPlayers.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20231102131015_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcPlayers.Models.Players", b =>
                {
                    b.Property<int>("Nummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nummer"));

                    b.Property<decimal>("Assist")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FödelseDatum")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Mål")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nummer");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
